// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AllowPing():Promise<string>;

export function ApplyTightVNCConfig():Promise<string>;

export function BulkInstall(arg1:Array<string>):Promise<Array<string>>;

export function BulkUninstall(arg1:Array<string>):Promise<Array<string>>;

export function ConnectNAS(arg1:string,arg2:string):Promise<string>;

export function DisconnectNAS():Promise<string>;

export function GetHardwareInfo():Promise<main.HardwareInfo>;

export function GetSoftwareList():Promise<Array<main.Software>>;

export function GetSystemStatus():Promise<string>;

export function InstallDocker():Promise<string>;

export function InstallSQLyog():Promise<string>;

export function InstallSoftware(arg1:string):Promise<string>;

export function RenamePC(arg1:string):Promise<string>;

export function SetBrandedWallpaper():Promise<string>;

export function SetSleepMode(arg1:number):Promise<string>;

export function SetStaticIP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetWallpaper(arg1:string):Promise<string>;

export function ShowThisPCIcon():Promise<string>;

export function SyncTime():Promise<string>;

export function TestSoftware(arg1:string):Promise<string>;

export function UninstallSoftware(arg1:string):Promise<string>;
