// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowPing() {
  return window['go']['main']['App']['AllowPing']();
}

export function ApplyTightVNCConfig() {
  return window['go']['main']['App']['ApplyTightVNCConfig']();
}

export function BulkInstall(arg1) {
  return window['go']['main']['App']['BulkInstall'](arg1);
}

export function BulkUninstall(arg1) {
  return window['go']['main']['App']['BulkUninstall'](arg1);
}

export function ConnectNAS(arg1, arg2) {
  return window['go']['main']['App']['ConnectNAS'](arg1, arg2);
}

export function DisconnectNAS() {
  return window['go']['main']['App']['DisconnectNAS']();
}

export function GetHardwareInfo() {
  return window['go']['main']['App']['GetHardwareInfo']();
}

export function GetSoftwareList() {
  return window['go']['main']['App']['GetSoftwareList']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function InstallDocker() {
  return window['go']['main']['App']['InstallDocker']();
}

export function InstallSQLyog() {
  return window['go']['main']['App']['InstallSQLyog']();
}

export function InstallSoftware(arg1) {
  return window['go']['main']['App']['InstallSoftware'](arg1);
}

export function RenamePC(arg1) {
  return window['go']['main']['App']['RenamePC'](arg1);
}

export function SetBrandedWallpaper() {
  return window['go']['main']['App']['SetBrandedWallpaper']();
}

export function SetSleepMode(arg1) {
  return window['go']['main']['App']['SetSleepMode'](arg1);
}

export function SetStaticIP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetStaticIP'](arg1, arg2, arg3, arg4);
}

export function SetWallpaper(arg1) {
  return window['go']['main']['App']['SetWallpaper'](arg1);
}

export function ShowThisPCIcon() {
  return window['go']['main']['App']['ShowThisPCIcon']();
}

export function SyncTime() {
  return window['go']['main']['App']['SyncTime']();
}

export function TestSoftware(arg1) {
  return window['go']['main']['App']['TestSoftware'](arg1);
}

export function UninstallSoftware(arg1) {
  return window['go']['main']['App']['UninstallSoftware'](arg1);
}
